stages:
  - build
  - test
  - quality
  - package
  - deploy-staging

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_REGISTRY: $CI_REGISTRY_IMAGE

cache:
  paths:
    - .m2/repository
  key: "$CI_JOB_NAME"

build:jdk8:
  stage: build
  image: openjdk:8-alpine
  script:
    - './mvnw $MAVEN_CLI_OPTS compile'

test:jdk8:
  stage: test
  image: openjdk:8-alpine
  script:
    - './mvnw $MAVEN_CLI_OPTS test'

code_quality:
  stage: quality
  image: docker:stable
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

package:
  stage: package
  image: openjdk:8-alpine
  services:
    - docker:stable-dind
  script:
    - apk add --no-cache docker
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - './mvnw $MAVEN_CLI_OPTS install -PbuildDocker -DskipTests=true -DpushImage'

deploy-staging:
  stage: deploy-staging
  image: docker:stable
  script:
    - scp -r docker ip172-18-0-51-bihm1906chi000b37l6g@direct.labs.play-with-docker.com:/root
    - scp docker-compose.yml ip172-18-0-51-bihm1906chi000b37l6g@direct.labs.play-with-docker.com:/root
    - ssh ip172-18-0-51-bihm1906chi000b37l6g@direct.labs.play-with-docker.com "docker-compose up -d"